/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FaceDetection;

import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import org.opencv.core.Core;
import org.opencv.core.Mat;
import org.opencv.core.MatOfRect;
import org.opencv.core.Point;
import org.opencv.core.Rect;
import org.opencv.core.Scalar;
import org.opencv.imgcodecs.Imgcodecs;
import org.opencv.imgproc.Imgproc;
import org.opencv.objdetect.CascadeClassifier;

/**
 *
 * @author ASUS
 */
public class Choosephoto extends javax.swing.JFrame {

    /**
     * Creates new form Choosephoto
     */
    public Choosephoto() {
        initComponents();
    }
    
    public void getImage(String path) {
        System.loadLibrary(Core.NATIVE_LIBRARY_NAME);
        CascadeClassifier faceDetector = new CascadeClassifier(); 
        faceDetector.load("haarcascade_frontalface_alt.xml");
       
        Mat image = Imgcodecs.imread(path);
       
        MatOfRect faceDetections = new MatOfRect();
        faceDetector.detectMultiScale(image, faceDetections);
        
        int numberDetect = 0;
        for (Rect rect: faceDetections.toArray()) {
           Imgproc.rectangle(image, new Point(rect.x, rect.y), new Point(rect.x + rect.width, rect.y + rect.height), new Scalar(0, 255, 0), 2);
           ++numberDetect;
        }
        
        if (numberDetect < 0 && numberDetect == 0) {
            jumlahwajah.setText("0");
        } else {
            jumlahwajah.setText(String.valueOf(numberDetect));
        }
       
        String filename = "output.jpg"; 
        Imgcodecs.imwrite(filename, image);
        ImageIcon icon = new ImageIcon(filename);
        
        Image img = icon.getImage();
        Image imgScale = img.getScaledInstance(framefoto.getWidth(), framefoto.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledIcon = new ImageIcon(imgScale);
        framefoto.setIcon(scaledIcon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        framefoto = new javax.swing.JLabel();
        namaphoto = new javax.swing.JLabel();
        label = new javax.swing.JLabel();
        jumlahwajah = new javax.swing.JLabel();
        pilihphoto = new javax.swing.JButton();
        infoapl = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplikasi Deteksi Wajah Choose File");

        framefoto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        framefoto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        namaphoto.setForeground(new java.awt.Color(0, 102, 102));
        namaphoto.setText("Photo yang dipilih");

        label.setForeground(new java.awt.Color(0, 102, 102));
        label.setText("Wajah Yang Terdeteksi Sebanyak:");

        jumlahwajah.setForeground(new java.awt.Color(0, 102, 102));
        jumlahwajah.setText("0");

        pilihphoto.setBackground(new java.awt.Color(0, 102, 102));
        pilihphoto.setForeground(new java.awt.Color(204, 255, 255));
        pilihphoto.setText("Choose Photo");
        pilihphoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pilihphotoActionPerformed(evt);
            }
        });

        infoapl.setBackground(new java.awt.Color(0, 102, 102));
        infoapl.setForeground(new java.awt.Color(204, 255, 255));
        infoapl.setText("Info Aplikasi");
        infoapl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infoaplActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("STLiti", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Created by Rakhimatulfitria Mekacahyani");

        jLabel2.setFont(new java.awt.Font("Stencil", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 102));
        jLabel2.setText("Aplikasi Pendeteksi Wajah");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(framefoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(infoapl, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(77, 77, 77)
                        .addComponent(namaphoto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pilihphoto, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jumlahwajah)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pilihphoto)
                            .addComponent(namaphoto)
                            .addComponent(infoapl, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)))
                .addComponent(framefoto, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jumlahwajah)
                    .addComponent(label)
                    .addComponent(jLabel1))
                .addGap(7, 7, 7))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pilihphotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pilihphotoActionPerformed
        // TODO add your handling code here:
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Image Files", "jpg", "png", "jpeg");
        JFileChooser filechooser = new JFileChooser();
        filechooser.setCurrentDirectory(new java.io.File("."));
        filechooser.setDialogTitle("Select one Image");
        filechooser.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
        filechooser.setFileFilter(filter);
        filechooser.setAcceptAllFileFilterUsed(false);
        
        if (filechooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            String getFilePath = filechooser.getSelectedFile().toString();
            namaphoto.setText(getFilePath);
            getImage(getFilePath);
        } else {
            namaphoto.setText("No Selection");
        }
    }//GEN-LAST:event_pilihphotoActionPerformed

    private void infoaplActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infoaplActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "# Aplikasi deteksi wajah yaitu suatu aplikasi pendeteksi jumlah wajah pada suatu frame ketika memilih photo dari perangkat.\n" +
"# Libraries yang digunakan yaitu :\n" +
"    - opencv\n" +
"    - jdk 17\n" +
"# Metode yang digunakan yaitu menggunakan metode dari paul viola dan micheal jones dengan fitur haarcascade sehingga\n" +
"jika ada sebuah image, face detector (haarcascade classifier akan mengklasifikasinya sebagai wajah atau bukan wajah.\n" +
"# Untuk menu about disini menggunakan pallate 'button' yang diberi nama info aplikasi menggunakan JOptionPane Show Message Dialog.\n"
+ "# Aplikasi ini sendiri menggunakan bahasa java dengan IDE neatbeans dan tool openCV.\n" +
"# Tutorial aplikasi : Ketika kita mengklik button 'Choose Photo' maka kita dapat memilih photo dari perangkat atau suatu file foto.\n Jika user tidak mengklik button 'Choose Photo' maka aplikasi belum bisa mendeteksi jumlah wajah pada photo yang dipilih dari perangkat.\n" +
"# Note : Aplikasi akan menghitung banyak wajah jika wajah pada photo dominan menghadap kedepan.\n" +
"# Referensi didapat dari beberapa link youtube dan juga google search.");
    }//GEN-LAST:event_infoaplActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Choosephoto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Choosephoto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Choosephoto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Choosephoto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Choosephoto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel framefoto;
    private javax.swing.JButton infoapl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jumlahwajah;
    private javax.swing.JLabel label;
    private javax.swing.JLabel namaphoto;
    private javax.swing.JButton pilihphoto;
    // End of variables declaration//GEN-END:variables
}
