/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;
import org.opencv.core.Core;
import org.opencv.core.Mat;
import org.opencv.core.MatOfByte;
import org.opencv.core.MatOfRect;
import org.opencv.core.Point;
import org.opencv.core.Rect;
import org.opencv.core.Scalar;
import org.opencv.core.Size;
import org.opencv.imgcodecs.Imgcodecs;
import org.opencv.imgproc.Imgproc;
import org.opencv.objdetect.CascadeClassifier;
import static org.opencv.objdetect.Objdetect.CASCADE_SCALE_IMAGE;
import org.opencv.videoio.VideoCapture;


/**
 *
 * @author ASUS
 */
public class cam extends javax.swing.JFrame {

    /**
     * Creates new form cam 
     */
  
    String source = "haarcascade_frontalface_alt.xml"; 
  
    CascadeClassifier faceDetector = new CascadeClassifier(source);
    
    
    public cam() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dasar = new javax.swing.JPanel();
        captures = new javax.swing.JPanel();
        start = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jmlcounting = new javax.swing.JLabel();
        note = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        infoaplikasi = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplikasi Deteksi Wajah");
        setBackground(new java.awt.Color(153, 255, 255));

        dasar.setBackground(new java.awt.Color(204, 255, 204));
        dasar.setPreferredSize(new java.awt.Dimension(650, 500));
        dasar.setLayout(null);

        captures.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout capturesLayout = new javax.swing.GroupLayout(captures);
        captures.setLayout(capturesLayout);
        capturesLayout.setHorizontalGroup(
            capturesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 648, Short.MAX_VALUE)
        );
        capturesLayout.setVerticalGroup(
            capturesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 289, Short.MAX_VALUE)
        );

        dasar.add(captures);
        captures.setBounds(0, 63, 650, 291);

        start.setBackground(new java.awt.Color(0, 102, 102));
        start.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        start.setText("Start Counting");
        start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startActionPerformed(evt);
            }
        });
        dasar.add(start);
        start.setBounds(0, 20, 119, 37);

        jLabel1.setBackground(new java.awt.Color(0, 102, 102));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Jumlah wajah yang terdeteksi :");
        dasar.add(jLabel1);
        jLabel1.setBounds(250, 360, 230, 20);

        jmlcounting.setBackground(new java.awt.Color(0, 102, 102));
        jmlcounting.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jmlcounting.setText("Wajah tidak terdeteksi");
        dasar.add(jmlcounting);
        jmlcounting.setBounds(480, 360, 170, 23);

        note.setFont(new java.awt.Font("Tahoma", 3, 8)); // NOI18N
        note.setText("Click start first  ");
        dasar.add(note);
        note.setBounds(0, 10, 80, 10);

        jLabel2.setFont(new java.awt.Font("STXingkai", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 102));
        jLabel2.setText("created by Rakhimatulfitria Mekacahyani");
        dasar.add(jLabel2);
        jLabel2.setBounds(0, 400, 250, 21);

        infoaplikasi.setBackground(new java.awt.Color(0, 102, 102));
        infoaplikasi.setFont(new java.awt.Font("Stylus BT", 1, 14)); // NOI18N
        infoaplikasi.setText("Info Apl");
        infoaplikasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infoaplikasiActionPerformed(evt);
            }
        });
        dasar.add(infoaplikasi);
        infoaplikasi.setBounds(550, 10, 90, 27);

        jLabel3.setFont(new java.awt.Font("Stencil", 0, 30)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 102));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Look at To Camera");
        dasar.add(jLabel3);
        jLabel3.setBounds(170, 10, 320, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dasar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dasar, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startActionPerformed
      
        
        (new Thread(){
            public void run(){
                VideoCapture capture = new VideoCapture(0);
        
                MatOfRect rostros = new MatOfRect();
                MatOfByte mem = new MatOfByte();
                
                Mat frame = new Mat();
                Mat frame_gray = new Mat();
                
                Rect[] facesArray;      
                Graphics g;
                BufferedImage buff = null;

                
                while(capture.read(frame)){
                    if(frame.empty()){
                        System.out.println("No face detection");
                        break;
                    }else{
                        try {
                            g = captures.getGraphics();
                            Imgproc.cvtColor(frame, frame_gray, Imgproc.COLOR_BGR2GRAY);
                            Imgproc.equalizeHist(frame_gray, frame_gray);
                            double w = frame.width();
                            double h = frame.height();
                            faceDetector.detectMultiScale(frame_gray, rostros, 1.1, 2, 0|CASCADE_SCALE_IMAGE, new Size(30, 30), new Size(w, h) );
                            facesArray = rostros.toArray();
                            System.out.println("Wajah yang terdeteksi: "+facesArray.length);
                         
                            for (int i = 0; i < facesArray.length; i++) {
                               
                                Point center = new Point((facesArray[i].x + facesArray[i].width * 0.5), 
                                        (facesArray[i].y + facesArray[i].height * 0.5));
                                Imgproc.ellipse(frame, 
                                        center, 
                                        new Size(facesArray[i].width * 0.5, facesArray[i].height * 0.5), 
                                        0, 
                                        0, 
                                        360, 
                                        new Scalar(255, 0, 255), 4, 8, 0);
                             
                                Mat faceROI = frame_gray.submat(facesArray[i]);
                                Imgproc.rectangle(frame,
                                        new Point(facesArray[i].x,facesArray[i].y),
                                        new Point(facesArray[i].x+facesArray[i].width,facesArray[i].y+facesArray[i].height),
                                        new Scalar(123, 213, 23, 220));
                              //  Imgproc.putText(frame, "Width: "+faceROI.width()+" Height: "+faceROI.height()+" X = "+facesArray[i].x+
                               //         " Y = "+facesArray[i].y, new Point(facesArray[i].x, facesArray[i].y-20), 1, 1, new Scalar(255,255,255));
                                Imgproc.putText(frame, "Wajah Terdeteksi"
                                     , new Point(facesArray[i].x, facesArray[i].y-20), 1, 1, new Scalar(255,255,255));
                            }
                           
                            int no= facesArray.length;
                            jmlcounting.setText(String.valueOf(no));
                            
                             Imgcodecs.imencode(".bmp", frame, mem);
                            Image im = ImageIO.read(new ByteArrayInputStream(mem.toArray()));
                            buff = (BufferedImage) im;
                            if(g.drawImage(buff, 0, 0, captures.getWidth(), captures.getHeight() , 0, 0, buff.getWidth(), buff.getHeight(), null)){
                            }
                            
                            
                            
                        } catch (Exception ex) {
                   
                        }
                    }
                    
                }
            }
            
        }).start();
        
        
    }//GEN-LAST:event_startActionPerformed

    private void infoaplikasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infoaplikasiActionPerformed
        // TODO add your handling code here:
        ImageIcon Icons = new ImageIcon("C:Downloads/th (2).jpg");
        JOptionPane.showMessageDialog(null, "# Aplikasi deteksi wajah yaitu suatu aplikasi pendeteksi jumlah wajah pada suatu frame ketika camera laptop menyala.\n" +
"# Libraries yang digunakan yaitu :\n" +
"    - opencv\n" +
"    - jdk 17\n" +
"# Metode yang digunakan yaitu menggunakan metode dari paul viola dan micheal jones dengan fitur haarcascade sehingga\n" +
"jika ada sebuah image, face detector (haarcascade classifier akan mengklasifikasinya sebagai wajah atau bukan wajah.\n" +
"# Untuk menu about disini menggunakan pallate 'button' yang diberi nama info aplikasi menggunakan JOptionPane Show Message Dialog.\n"
+ "# Aplikasi ini sendiri menggunakan bahasa java dengan IDE neatbeans dan tool openCV.\n" +
"# Tutorial aplikasi : Ketika kita mengklik button 'start counting' maka kamera laptop akan menyala sehingga setiap wajah yang masuk kedalam frame akan dijumlahkan sesuai banyak wajah yang terdeteksi oleh aplikasi.\n Jika user tidak mengklik button 'start counting' maka kamera laptop tidak akan menyala sehingga aplikasi belum bisa mendeteksi jumlah wajah pada frame.\n" +
"# Note : Jika wajah masuk kedalam frame maka wajah akan terdeteksi sebagai 'Wajah Terdeteksi' yang nantinya akan dihitung jumlahnya.\n dan juga diharapkan ketika menghadap kamera wajah tidak miring ke kanan maupun kekiri (menghadap kedepan).\n" +
"# Referensi didapat dari beberapa link youtube dan juga google search.", "Info Aplikasi", JOptionPane.INFORMATION_MESSAGE, Icons);
    }//GEN-LAST:event_infoaplikasiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        System.loadLibrary(Core.NATIVE_LIBRARY_NAME);
        
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cam().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel captures;
    private javax.swing.JPanel dasar;
    private javax.swing.JButton infoaplikasi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jmlcounting;
    private javax.swing.JLabel note;
    private javax.swing.JButton start;
    // End of variables declaration//GEN-END:variables
}
